name: Fork Sync


on:
  push:
   schedule:
    - cron: '* */24 * * *' # 每3小时触发, 对于一些更新不那么频繁的项目可以设置为每天一次, 低碳一点
jobs:
  sync:

    runs-on: ubuntu-latest
    
    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ohmyzsh
          base: master
          head: master

